### ISSUE TITLE
Link broken on https://www.celltypist.org/faq to (Basic_celltype_information.xlsx)

### ISSUE THREAD

**Issue by lubianat** [Teichlab/celltypist_wiki#2]
It points to https://github.com/Teichlab/celltypist_wiki/tree/main/atlases/Pan_Immune_CellTypist/tables , 

I guess it should point to https://github.com/Teichlab/celltypist_wiki/blob/main/atlases/Pan_Immune_CellTypist/v2/tables/Basic_celltype_information.xlsx

**Comment by ChuanXu1** [comment]
@lubianat  The link in the website is outdated. I will fix it soon. Thank you

**Comment by ChuanXu1** [comment]
Thank you again for raising this. It has now been fixed.

**Comment by ChuanXu1** [comment]
It has now been fixed.
